socket_server: main.c Socket_Server.c  libanc/fd_send.c # libanc/fd_recv.c libanc/fd_send.c
	gcc -g -Wall -o socket_server main.c Socket_Server.c  libanc/fd_send.c # libanc/fd_send.c libanc/fd_send.c -Wall
